version: 2.1
jobs:
  build:
    docker:
    - image: circleci/node

    working_directory: ~/repo

    steps:
    - checkout
    - setup_remote_docker
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD quay.io
    - run: docker build -t quay.io/simonpasquier/react-redux-realworld-example-app:latest .
    - run: docker push quay.io/simonpasquier/react-redux-realworld-example-app:latest

workflows:
  version: 2
  master:
    jobs:
    - build:
        context: Quay
